//! Names that need no description on first use. Everyday words and the tools
//! any software reader knows. Anything project-specific belongs in the
//! `--known-names` file, which lives outside the repository.

/// Ordinary words that stand alone in prose or open a sentence by grammar
/// alone, never a name even when capitalised. `BUILT_IN` lists these so a
/// lone use of one, such as sentence-initial "The", is not itself reported;
/// but one of these heading an otherwise-unknown run proves nothing about
/// the run, unlike a real name such as "GitHub" heading "GitHub Apps".
const GENERIC_WORDS: &[&str] = &[
    "I",
    "The",
    "A",
    "An",
    "This",
    "That",
    "These",
    "Those",
    "It",
    "We",
    "You",
    "They",
    "He",
    "She",
    "No",
    "Yes",
    "Not",
    "None",
    "Nothing",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Ten",
    "Phase",
    "Step",
    "Item",
    "Option",
    "Part",
    "Point",
    "Round",
    "Section",
    "Table",
    "Figure",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "English",
    "Simplified",
    "Technical",
];

/// Whether `word` is a real known name rather than one of `GENERIC_WORDS`,
/// so it can carry an otherwise-unknown run that starts with it: "GitHub"
/// heading "GitHub Apps" keeps the whole run known, but "The" heading
/// "The Widget" does not, since "The" proves nothing about "Widget".
#[must_use]
pub fn is_name_head(word: &str) -> bool {
    BUILT_IN.contains(&word) && !GENERIC_WORDS.contains(&word)
}

/// Whether `word` is one of `GENERIC_WORDS`, so a caller can treat any other
/// known name, built in or added by a project, as a real name.
#[must_use]
pub fn is_generic_word(word: &str) -> bool {
    GENERIC_WORDS.contains(&word)
}

pub const BUILT_IN: &[&str] = &[
    // words that start sentences or stand alone in prose
    "I",
    "The",
    "A",
    "An",
    "This",
    "That",
    "These",
    "Those",
    "It",
    "We",
    "You",
    "They",
    "He",
    "She",
    "No",
    "Yes",
    "Not",
    "None",
    "Nothing",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Ten",
    "Phase",
    "Step",
    "Item",
    "Option",
    "Part",
    "Point",
    "Round",
    "Section",
    "Table",
    "Figure",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "English",
    "Simplified",
    "Technical",
    // platforms and languages
    "GitHub",
    "Git",
    "GitLab",
    "Bitbucket",
    "Windows",
    "macOS",
    "Linux",
    "Ubuntu",
    "Debian",
    "Alpine",
    "WSL",
    "Docker",
    "Intel",
    "Arm",
    "Apple Silicon",
    "Kubernetes",
    "PowerShell",
    "Bash",
    "Rust",
    "Cargo",
    "Go",
    "Python",
    "TypeScript",
    "JavaScript",
    "Node",
    "Bun",
    "Deno",
    "Java",
    "Kotlin",
    "Gradle",
    "Maven",
    "Dart",
    "Flutter",
    "Swift",
    "Android",
    "Apple",
    "Google",
    "Microsoft",
    "Amazon",
    "AWS",
    "Azure",
    "Cloudflare",
    "Markdown",
    "Unicode",
    "Internet",
    "Web",
    "Chrome",
    "Firefox",
    "Safari",
    "Edge",
    "Visual",
    "Studio",
    "Code",
    "VS",
    // coding agents and vendors
    "Claude",
    "Sonnet",
    "Opus",
    "Haiku",
    "Anthropic",
    "Codex",
    "OpenAI",
    "ChatGPT",
    "Copilot",
    "Gemini",
    "DeepSeek",
    "Cursor",
    "OpenCode",
    "Aider",
    // things a factory reader meets in every message
    "Actions",
    "Issues",
    "Projects",
    "Dockerfile",
    "README",
    "AGENTS",
    "SKILL",
    "CI",
    "PR",
    "URL",
];
